### ISSUE TITLE
Add Token Example

### ISSUE THREAD

**Issue by webeli** [MarketCap-Cash/SmartBCH-Token-List#1]
{
    "name": "Green Ben",
    "desc": "....",
    "address": "0x77CB87b57F54667978Eb1B199b28a0db8C8E1c0B",
    "symbol": "EBEN",
    "image": "link to image",
    "website": "https://benswap.cash/",
    "telegram": "....",
    "twitter": "..."
  }

**Comment by 1Crazymoney** [comment]
{
"name": "Global Trade Unit",
"address": "bitcoincash:qzdw2mq06vqnd3waarrc4pepruq3jtzmk5rnh3l2cc",
"symbol": "GTU",
"image": "
![LOGO MAKER GTU COLORS](https://user-images.githubusercontent.com/35787729/132603786-be6b62b3-f03f-466a-a45d-7015c43a33f5.png)
",
"website": "https://www.locopecuniainc.",
"telegram": "https://t.me/locopecuniainc",
}

**Comment by 1Crazymoney** [comment]
![LOGO MAKER GTU COLORS](https://user-images.githubusercontent.com/35787729/132606792-d60cf489-5064-45bd-9db0-a61c613678a5.png)

**Comment by webeli** [comment]
@1Crazymoney please only SEP20 tokens operating on SmartBCH.

**Comment by KonraToken** [comment]
{
"name": "Konra SEP20",
"address": "0x4F1480ba79F7477230ec3b2eCc868E8221925072",
"symbol": "KONRA",
"image": "http://konratoken.com/wp-content/uploads/2021/10/KONRA1.png",
"website": "http://konratoken.com",
"telegram": "Coming Soon",
"twitter": "https://twitter.com/Konratoken"
}


Please let me know if I did this right and if you need any additional information.

**Comment by webeli** [comment]
@KonraToken would prefer that you create a new issue, otherwise this will get bloated.
