### ISSUE TITLE
FLEX Coin

### ISSUE THREAD

**Issue by EwelinaMI5** [MarketCap-Cash/SmartBCH-Token-List#10]
{
"name": "FLEX Coin",
"address": "0x98Dd7eC28FB43b3C4c770AE532417015fa939Dd3",
"symbol": "FLEX",
"image": "https://cdnm.coinflex.com/wp-content/uploads/20210913102344/coinflex-logo.png",
"website": "https://coinflex.com/flex-coin/",
"telegram": "https://t.me/coinflex_EN",
"twitter": "https://twitter.com/coinflexdotcom"
}

**Comment by webeli** [comment]
Please no fake coins.

**Comment by EwelinaMI5** [comment]
We appreciate your care for listing authenticity. What are the requirements to prove the listing details are genuine?

**Comment by EwelinaMI5** [comment]
@webeli Is FLEX Coin now also queued for adding? You can verify here https://coinflex.com/support/flex-coin-now-live-on-smartbch/

**Comment by webeli** [comment]
@EwelinaMI5 yes will list FLEX Coin asap, need some liquidity on Benswap first, or i can't display any data. Thanks for the info!

**Comment by webeli** [comment]
Added.
