### ISSUE TITLE
Updated Social + Website info for Wojak

### ISSUE THREAD

**Issue by Wojakso** [MarketCap-Cash/SmartBCH-Token-List#101]
"WOJAK": {
    "address": "0x8d7ea0ec6cab515463121a3c70df541f2f534909",
    "desc": "The first ever automatic-rewards token on SmartBCH that pays FlexUSD just for holding, Use 12% Slippage when buying or selling Wojak",
    "image": "https://www.marketcap.cash/_next/image?url=%2Fwojak.jpeg&w=96&q=75",
    "name": "WOJAK",
    "symbol": "WOJAK",
    "websites": ["https://wojak.so"],
    "twitter": "https://twitter.com/wojak_official",
    "telegram": "https://t.me/wojakbch"

**Comment by webeli** [comment]
Updated.
