### ISSUE TITLE
DAIQUIRI-FLEXUSD Liquidity in Marketcap

### ISSUE THREAD

**Issue by tropicalfi** [MarketCap-Cash/SmartBCH-Token-List#105]
Hello there,
Merry Christmas and thank you for listing tropical finance in Marketcap 🎄😄
As our token has 2 liquidities, daiquiri-BCH and Daiquiri-Flexusd, I would ask you if it’s possible to list that liquidity too, since Flexusd paid has $250k+ liquidity too, and so the DAIQUIRI token has a total of $500k+ liquidity, I see now is only listed the BCH pair

thanks in advance

**Comment by webeli** [comment]
Unfortunately we currently only support BCH-TOKEN pairs. We're evaluating supporting others like flexUSD f.e.
