### ISSUE TITLE
flexUSD

### ISSUE THREAD

**Issue by EwelinaMI5** [MarketCap-Cash/SmartBCH-Token-List#11]
{
"name": "flexUSD",
"address": "0x7b2B3C5308ab5b2a1d9a94d20D35CCDf61e05b72",
"symbol": "flexUSD",
"image": "https://cdnm.coinflex.com/wp-content/uploads/20201113041028/flexUSD%402x.png",
"website": "https://coinflex.com/flexUSD",
"telegram": "https://t.me/coinflex_EN",
"twitter": "https://twitter.com/coinflexdotcom"
}

**Comment by webeli** [comment]
Please no fake coins.

**Comment by webeli** [comment]
Well, seems to be the real flexUSD, im sorry, confirmed on https://coinflex.com/support/flexusd-now-live-on-smartbch/?utm_campaign=flexUSD&utm_content=179758883&utm_medium=social&utm_source=twitter&hss_channel=tw-1080702641141772288

Adding it!

**Comment by webeli** [comment]
Thank you @EwelinaMI5

**Comment by EwelinaMI5** [comment]
Thanks @webeli :+1:
