### ISSUE TITLE
Please add BabyLaw token 

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#111]
{
"name": "BabyLaw",
"desc": ". BabyLaw is one of the first rewards tokens on the sBCH network, created by Admirers of the LawPunk ecosystem and coin. Prizes given to holders regularly and plans for NFTs and games in the future.",
"address": "0x02905c38B3CFBAE5255104C7a6FD10EF78225f35",
"symbol": "BABYLAW",
"image": "
![7B3EC9CE-080F-4E5B-99A6-8AC8B865F5CC](https://user-images.githubusercontent.com/90625656/147700937-6f7e29a8-6c72-41e8-bcbb-efe38e2154cf.jpeg)
",
"website": "https://babylawbch.com/",
"telegram": "https://t.me/BabyLawBCH",
"twitter": "https://twitter.com/babylawbch?s=21"
“Email”: “ Raycales@babylawbch.com”
}

**Comment by raycales** [comment]
There's a Small error there, the Old website address was added, the new website is www.babylawbch.com

**Comment by Diggle187** [comment]
> There's a Small error there, the Old website address was added, the new website is [www.babylawbch.com](http://www.babylawbch.com)

Hi Ray, I’ve edited it to the new website thanks

**Comment by webeli** [comment]
@Diggle187 is this your 4th token with burning mechanics? Why not focusing on a single one?

**Comment by raycales** [comment]
This is my token mate, he just filled the listing in for me, to aid in the
listing

**Comment by raycales** [comment]
I’ve been grinding for the last 6 days in hope of a listing. I updated my
website got listed in coinhunters and all the other similar sites, had
numerous giveaways to keep the hype up, but the only one that really
matters for us is getting listed in marketcap, the volume has slowed down a
bit now but all the main investors are holding the floor at 30k market cap.
our whole community are craving  a listing and so am I. I hope marketcap
can list us it would be a big boost to group moral and personal moral lol.

**Comment by webeli** [comment]
@raycales ok, where do you have liquidity?

**Comment by raycales** [comment]
I burned it I will look back my transactions

**Comment by webeli** [comment]
You need liquidity on a DEX for us to pull data.

**Comment by raycales** [comment]
Alright sorry yeah it’s on mist

**Comment by webeli** [comment]
Added.

**Comment by Diggle187** [comment]
Hi Webeli, none of these coins have been mine I’m just helping the Devs out as I know how to correctly fill in the form (I take no payment or anything like that). I do plan to launch a coin in the future but want to make sure I have the platform ready to go when I do. Sorry for any confusion and thanks for all the great work you are doing. 


Sent from Yahoo Mail for iPhone


On Thursday, December 30, 2021, 8:39 pm, webeli ***@***.***> wrote:




@Diggle187 is this your 4th token with burning mechanics? Why not focusing on a single one?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by raycales** [comment]
Yeah Diggle runs SmartBCH moon shots page he’s a massive help for the
community, I wouldn’t of got as far as I have in 6 days if it was for
Diggle. Thanks mate your a legend,
