### ISSUE TITLE
Please add CST Image and description 

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#115]
![C7945281-692C-4419-B023-954801C719C0](https://user-images.githubusercontent.com/90625656/147802623-3f77706e-440c-46d8-987e-2d364efecca6.jpeg)

Description -  CST is the utility, community reward, and governance token of CryptoSorted, a community-owned crypto media publications project which rewards its holders with weekly BCH airdrop.

**Comment by webeli** [comment]
Done.
