### ISSUE TITLE
Image for TEEF Token

### ISSUE THREAD

**Issue by GiverofMemory** [MarketCap-Cash/SmartBCH-Token-List#116]
![T4](https://user-images.githubusercontent.com/78986433/147803844-20490ad9-1962-47de-8b9b-10ca90ebb804.png)

Liquidity on mistswap.  Product token given as a reward for product purchases at teefpowder.com

tokens.json update is here **https://github.com/MarketCap-Cash/SmartBCH-Token-List/pull/117**

**Comment by webeli** [comment]
Added

**Comment by GiverofMemory** [comment]
> Added

Thank you!
