### ISSUE TITLE
Please add SEP - 20 shiba BCH

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#12]
edited 

"name": "Shiba BCH",
"address": "0x2f309b9d47b1ce7f0ec30a26bab2deab8c4ea5e9",
"symbol": "SHIBBCH",
"image": "
![68FAF356-4037-4730-AC5C-A777AE258B76](https://user-images.githubusercontent.com/90625656/133097678-8859a556-6dde-49bd-8c90-12d75af4f81f.png)
",
"website": "",
"telegram": "https://t.me/ShibaCashBCH",
"twitter": "..."
}

**Comment by Diggle187** [comment]
Can we get this on marketcap.cash please buddy

**Comment by webeli** [comment]
Done.
