### ISSUE TITLE
Please Add Eve token 

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#120]
Name - EVE (expected value in entropy)
Project Description - p2p electronic cash system, further use cases being explored include poker chips
Contract - 0x7b82A3b1417Cd21E67f745917a80cC0f53277B8C
Symbol - EVE
Website - evecoin.info
Telegram - https://t.me/+MMk8E7h9wHRlOTlh
Twitter - twitter.com/damonwedel
Which DEX is your liquidity on? - Benswap
Token image - ![27AFA890-77AD-4ACD-A1AF-C35931621CB0](https://user-images.githubusercontent.com/90625656/147863151-d67a6812-d92c-47ca-8a30-830ef62f5269.jpeg)

**Comment by webeli** [comment]
Added.
