### ISSUE TITLE
Update $METADOR Logo

### ISSUE THREAD

**Issue by Metador-SMARTBCH** [MarketCap-Cash/SmartBCH-Token-List#121]
Hello, Webeii, Kindly update $Metador Logo on marketcap.cash. 
Thank you.
![logo-small](https://user-images.githubusercontent.com/95138869/147872983-e885fb6d-5667-4212-bc2e-a988bcdf6533.png)

**Comment by Diggle187** [comment]
Are you able to put this in as a Pull request please

**Comment by webeli** [comment]
Updated the image.
