### ISSUE TITLE
Please Add SUN CASH

### ISSUE THREAD

**Issue by bitcoinfly** [MarketCap-Cash/SmartBCH-Token-List#124]
Name-SUN (Sun Cash DAO)
Project Description-Decentralized Autonomous Organization Electronic Cash
Contract-0x291361E2619Cd0fbfD880bE3c02926CfDd3c6a9F
Symbol-SUN
Telegram-https://t.me/smartsuncash
Twitter-https://twitter.com/SunCash_DAO
Which DEX is your liquidity on? -Benswap，MISTswap
<img width="417" alt="IMG_0269" src="https://user-images.githubusercontent.com/67223784/148026792-e321ace2-d283-4564-854b-9781121422f6.PNG">

**Comment by bitcoinfly** [comment]
<img width="417" alt="SUNCASH" src="https://user-images.githubusercontent.com/67223784/148033771-5ebc0b7a-434f-4f39-ae37-15353fbb2c3a.PNG">

**Comment by bitcoinfly** [comment]
Hello, is there a problem with the information I submitted

**Comment by webeli** [comment]
Added.
