### ISSUE TITLE
add FM token to marketcap.cash

### ISSUE THREAD

**Issue by FMTLOL** [MarketCap-Cash/SmartBCH-Token-List#129]
{
"name": "FOLLOW ME",
"desc": "Follow Me is a DeFi-based social media reward token. The token is used to create campaigns and increase the user's popularity",
"address": "0x03943C3ef00d92e130185CeBC0bcc435Def2cC94",
"symbol": "FM",
"image": "<a href="https://imgur.com/HOoGIB2"><img src="https://i.imgur.com/HOoGIB2.png" title="source: imgur.com" /></a>",
"website": "https://fmt.lol",
"twitter": "https://twitter.com/fmtlol",
"facebook": "https://www.facebook.com/fmtlol",
"telegram": "https://t.me/fmtlol",
"discord": "https://discord.gg/DNkStvC7vp",
"Liquidity": "https://app.mistswap.fi/swap?outputCurrency=0x03943C3ef00d92e130185CeBC0bcc435Def2cC94"
}

**Comment by webeli** [comment]
Added.
