### ISSUE TITLE
Please Add Sep-20 Monkey Cash 

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#13]
edited 
{
"name": "Monkey Cash",
"address": "0x778C1c04D68c74FfdECBc0950d51033699c8Eb0B",
"symbol": "MCASH",
"image": "
![9D6090E1-197A-4D2D-A0F1-494C09D1D6B8](https://user-images.githubusercontent.com/90625656/133509590-9ea386be-32e0-4530-adda-46fd48a8afbf.jpeg)
",
"website": "http://imonkey.cash/",
"telegram": "https://t.me/imonkeycash",
"twitter": "@imonkeycash"
}

**Comment by webeli** [comment]
Added.

**Comment by Diggle187** [comment]
I put this request in on behalf of one of their team (who claimed he didn't know it was a scam afterwards). I had no affiliation with Monkey cash and was left out of pocket when it rugged as well. No good deed goes unpunished they say :/
