### ISSUE TITLE
TEEF Liquidity moved to Muesliswap

### ISSUE THREAD

**Issue by GiverofMemory** [MarketCap-Cash/SmartBCH-Token-List#133]
Right now marketcap.cash was only tracking teef token on mistswap, liquidity moved to muesli instead.  Thanks.

Thanks.

0xe691221eD15BA1E2491B552db955191789d9a8d9

**Comment by GiverofMemory** [comment]
Please expedite this, I am getting complaints that I "rug pulled" since your list can't tell when liquidity is moved to another dex...

**Comment by webeli** [comment]
Updated.

**Comment by GiverofMemory** [comment]
> Updated.

Thank you!  Assuming the current situation of 4 tokens showing $0 liquidity is just the update in progress.
