### ISSUE TITLE
Add PumpParrots [PUMP] to token list

### ISSUE THREAD

**Issue by mjrincon** [MarketCap-Cash/SmartBCH-Token-List#135]
{
"name": "PumpParrots",
"desc": "An open NFT Gaming Project on SmartBCH",
"address": "0x20539E145b86A388683CB067dE576303aEC6DdE3",
"symbol": "PUMP",
"image": "mistswapdex/assets/blockchains/smartbch/assets/0x20539E145b86A388683CB067dE576303aEC6DdE3/logo.png",
"website": "https://www.pumpitup.cash/",
"discord": "https://discord.com/invite/ZSX78ah4",
"twitter": "https://twitter.com/PumpParrots"
"liquidity": "https://analytics.mistswap.fi/pairs/0xbd4d2abf65591dd60f786926efc02b1d23414d3e"
}

**Comment by Diggle187** [comment]
Please put this in as a pull request

**Comment by mjrincon** [comment]
Done thanks!

**Comment by webeli** [comment]
@mjrincon added, but you need to increase the BCH pool liquidity to more than 0.5 BCH (it's 0.4 now) for our system to pull data.
