### ISSUE TITLE
Add The Dosh

### ISSUE THREAD

**Issue by TheDosh** [MarketCap-Cash/SmartBCH-Token-List#136]
{ “Name” - “The Dosh”
“Project Description” - “Dosh is a platform planning to build a buy back platform ”
“Contract” - “0x79Eff270d504c323bEBA56990Ed9bEa6c53927bB”
“Symbol” - “DOSH”
“Website” - “https://wiggumdosh.in”
“Telegram” - “https://t.me/doshBCH”
“Twitter” - “https://twitter.com/wiggumdosh ”
“Which DEX is your liquidity on” - “dex.benswap.cash ”
“Token image” -
![image](https://user-images.githubusercontent.com/97343876/148645528-c159c164-a2b2-40ed-a495-da31a6db7ea2.png)

**Comment by Diggle187** [comment]
Please put this in as a pull request

**Comment by webeli** [comment]
Website not working, re-open when website working again.
