### ISSUE TITLE
Update the $DONER icon.

### ISSUE THREAD

**Issue by jQrgen** [MarketCap-Cash/SmartBCH-Token-List#139]
Please update the $DONER icon.

See: https://github.com/MarketCap-Cash/SmartBCH-Token-List/pull/138

**Comment by webeli** [comment]
@jQrgen updated, but please provide more than 0.5 BCH liquidity otherwise our system wont pull any new data.

**Comment by jQrgen** [comment]
@webeli Ok, thanks. Do you track liquidity for other pairs such as FlexUSD/$DONER ?

**Comment by jQrgen** [comment]
The community added liquidity now <3
