### ISSUE TITLE
Please Add Sep-20 MECH MASTER

### ISSUE THREAD

**Issue by bnan131** [MarketCap-Cash/SmartBCH-Token-List#14]
{
"name": "MECH MASTER",
"address": "0xbb76dDAF4F763790809E78B9A9520DAa2c3a1948",
"symbol": "MECH",
"image": "https://chainbroker.io/media/projects/mech-master/mech-master.jpg",
"website": " https://mechmaster.io/#/ " ,
"telegram": "https://t.me/MechMaster_Official",
"twitter": "https://twitter.com/MechMaster_IO"
}

**Comment by webeli** [comment]
Hi @bnan131 we can only add it when you have liquidity on a DEX (like on Benswap.Cash), otherwise i can't display any data. When you have liquidity i can add it.

**Comment by webeli** [comment]
Still very low liquidity, will add it when there's more.
