### ISSUE TITLE
Add BCHDAO to token list

### ISSUE THREAD

**Issue by bchdao** [MarketCap-Cash/SmartBCH-Token-List#143]
"DAOer": {
    "name": "DAOer",
    "desc": "(DAOer) BCHDAO, which comes from the SmartBCH enthusiast community, we want to help quality projects on SmartBCH, gain more exposure. Our website: bchdao.cash, currently under localization development by way of Apache, is expected to be available to you in Q2 2022.",
    "address": "0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2",
    "symbol": "BCHDAO",
    "image": "https://assets.mistswap.fi/blockchains/smartbch/assets/0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2/logo.png",
    "website": "https://bchdao.cash",
    "telegram": "https://t.me/bchdao_sBCH_en"
    "twitter": "https://twitter.com/bchdaocash",
    "email": "smartbch@bchdao.cash",
    "github": "https://github.com/bchdao"
  }

“Which DEX is your liquidity on” - “https://app.mistswap.fi/swap?inputCurrency=0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2&outputCurrency=”
See:[#157 ]
![logo](https://user-images.githubusercontent.com/88589228/149663909-aa993ba8-a93c-4c85-9f22-591871aadb61.png)

**Comment by bchdao** [comment]
![logo](https://user-images.githubusercontent.com/88589228/149658927-bb09b120-3e01-4489-8cc9-b3b8e0d2afe1.png)

**Comment by bchdao** [comment]
Thanks to the reviewers for helping me to pass the review.
I made a mistake in my previous action of pulling the request, which resulted in a change in the original code page, so please ignore my previous mistake. Thank you.
I have resubmitted the pull request action.

**Comment by Diggle187** [comment]
Can you put this in as a Pull Request please

**Comment by bchdao** [comment]
> Can you put this in as a Pull Request please

**Hi, Diggle187.
I have added a pull request, did I do it incorrectly? Please enlighten me. Thank you.**
![image](https://user-images.githubusercontent.com/88589228/149805850-e9ac4eea-89db-49f9-a29c-7edb812b9b8c.png)

**Comment by bchdao** [comment]
> Can you put this in as a Pull Request please

Hi~ Diggle187 
I see that Kaiju tokens have been added, but BCHDAO has not been added on? What could be the reason for this? I have resubmitted the pull request, please provide a technical suggestion, thanks.
By the way, we have more than 22 BCH of liquidity in mitswap.
Please help to check, the reason why it can't be added to Marketcap list, thanks.
![image](https://user-images.githubusercontent.com/88589228/149914606-7d460883-ddce-4d19-9ece-149b99e027f6.png)

**Comment by bchdao** [comment]
> Can you put this in as a Pull Request please
Hi~ Diggle187,
Is there anything else I need to do? 
Thank you~

**Comment by webeli** [comment]
@bchdao can you please explain more in detail on what you're planning to do with this project? What's the timer about on the website?

**Comment by bchdao** [comment]
When the bchdao.cash website gains a certain number of users, we will choose to establish joint promotions with developers of quality projects in the form of graphics/videos.
Thank you, Webeli.

**Comment by webeli** [comment]
Would it be possible for you to pick another original name? I feel newbies would get confused and think you are the official DAO of BCH. If you change your name i can list you on the spot. It's just confusing because BCH don't have an official DAO.

**Comment by bchdao** [comment]
> Would it be possible for you to pick another original name? I feel newbies would get confused and think you are the official DAO of BCH. If you change your name i can list you on the spot. It's just confusing because BCH don't have an official DAO.

Thank you, Webeli.
Since the BCHDAO token name is already live on Mist it is not possible to change the token name, what do I need to do to get listed on marketcap?
Do I just need to change the "name" field in the submission to marketcap?
If I change the main description from "BCHDAO" to "DAOer", will it pass the review?
https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/143#issue-1105029177

**Comment by webeli** [comment]
Added.
