### ISSUE TITLE
SPACE

### ISSUE THREAD

**Issue by starstrain** [MarketCap-Cash/SmartBCH-Token-List#148]
{
  "name": "SPACE",
  "desc": "NFT Marketplace and Collection powered by SPACE",
  "address": "0xB0c59E4B2249123b014c1C39D012BFCA58a8E1b7",
  "symbol": "SPACE",
  "image": "https://timefoundation.net/Space-Finance/images/SPACEsBCHCoin.png",
  "websites": ["https://timefoundation.net/Space-Finance/"],
  "telegram": "https://t.me/SpaceOfficialFinance",
  "twitter": "https://twitter.com/SpaceTimeFi",
  "github": "https://github.com/starstrain/Space-Finance"
}

**Comment by Diggle187** [comment]
Liquidity is on Mistswap for this one

**Comment by webeli** [comment]
Added
