### ISSUE TITLE
FARM

### ISSUE THREAD

**Issue by farmbch** [MarketCap-Cash/SmartBCH-Token-List#149]
{
  "name": "FARM",
  "desc": "The first token that allows you to see a 24/7 streaming of a FARM",
  "address": "0xbd53a8fEBe9bdceacCEfaA45dC714bA718151c6B",
  "symbol": "FARM",
  "image": "https://thefarm.cash/assets/img/logo.png",
  "websites": ["https://thefarm.cash/"],
  "telegram": "https://t.me/thefarmbch"
}

**Comment by webeli** [comment]
What is this? Do you only watch a farm? Can you please elaborate.

**Comment by farmbch** [comment]
Yes

**Comment by webeli** [comment]
Done.
