### ISSUE TITLE
Please add NomadCoin (NOMAD) token

### ISSUE THREAD

**Issue by nomadghada** [MarketCap-Cash/SmartBCH-Token-List#15]
{
"name": "NomadCoin",
"address": "0xEE1bA4e4C266C7cc071f5de5e6dc90965E608087",
"symbol": "NOMAD",
"image": "https://nomadcoinproject.files.wordpress.com/2021/09/nomad_logo-round.png?w=150",
"website": "https://nomadcoinproject.wordpress.com/",
"read.cash": "https://read.cash/c/nomadcoin-00dd",
"noise.cash": "https://noise.cash/c/nomadcoin-xlpnq67l",
}

**Comment by nomadghada** [comment]
Can you please add this to marketcap.cash

**Comment by webeli** [comment]
There's very low liquidity, will add it when there's more.
