### ISSUE TITLE
Update Token (Expected Value in Entropy)

### ISSUE THREAD

**Issue by PokerJ0k3r** [MarketCap-Cash/SmartBCH-Token-List#152]
Add any update here. add EVE/WBCH mistswapLP address 
![1E513D34-32F8-498E-88DE-7334E15669BC_4_5005_c](https://user-images.githubusercontent.com/96651874/151439982-de115027-4c38-4ecd-87ed-6996c9accd59.jpeg)

[
](https://analytics.mistswap.fi/pairs/0x380094357328488781a0fb31c271a13db7357c1e)

**Comment by PokerJ0k3r** [comment]
https://analytics.mistswap.fi/pairs/0x380094357328488781a0fb31c271a13db7357c1e

**Comment by webeli** [comment]
Done.
