### ISSUE TITLE
Add Friend to list

### ISSUE THREAD

**Issue by ag076810** [MarketCap-Cash/SmartBCH-Token-List#159]
{
  "name": "Friend",
  "desc": "FRN aims to be the most widely distributed token on sBCH",
  "address": "0x4592b88618119e55e37ffcb28ede02bef6f3c5ba",
  "symbol": "FRN",
  "image": "https://frnbch.netlify.app/assets/images/frn_logo.png",
  "websites": "https://frnbch.netlify.app/",
  "telegram": ".https://t.me/FriendDAO",
  "twitter": "https://twitter.com/Friend_sBCH",
}

“Which DEX is your liquidity on : https://app.mistswap.fi/swap?outputCurrency=0x4592b88618119e55e37ffcb28ede02bef6f3c5ba

**Comment by webeli** [comment]
Added.
