### ISSUE TITLE
dogeking

### ISSUE THREAD

**Issue by xiaohu555564** [MarketCap-Cash/SmartBCH-Token-List#160]
{
  "name": "dogeking",
  "desc": "....",
  "address": "0xB362c037c4130D3310a439962FA455ae38aF24e5",
  "symbol": "dogeking",
  "image": "![1644393012(1)](https://user-images.githubusercontent.com/94718131/153146722-96d1eb6e-3f37-4fd8-a622-fbe9094d9210.jpg)",
  "websites": ["https://dogeking.cash/"],
  "telegram": "@smartbchdogeking",
  "twitter": "...",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
Website not working.

**Comment by webeli** [comment]
No answer in 15 days, closing this. Please reopen if still relevant.
