### ISSUE TITLE
FIBONACCI

### ISSUE THREAD

**Issue by SankarSrinivasan1** [MarketCap-Cash/SmartBCH-Token-List#163]
{
  "name": "Fibonacci",
  "desc": "Fibonacci is a tipping token, and converted from SLP. No token sales. Anybody can participate in our telegram group @ganniumtokengroup and earn free fibonacci tokens. Use Ranch in benswap to earn rewards",
  "address": "0x78a43b1A7D7e3824428098e699ddB116d1870307",
  "symbol": "FIBONACCI",
  "image": "https://github.com/SankarSrinivasan1/fibonacci/blob/main/contract/0x78a43b1A7D7e3824428098e699ddB116d1870307.png",
  "websites": ["https://github.com/SankarSrinivasan1/fibonacci"],
  "telegram": "https://t.me/ganniumtokengroup",
  "twitter": "https://twitter.com/SankarSriniCMP",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
Is there liquidity?

**Comment by SankarSrinivasan1** [comment]
> Is there liquidity?

Yes. Please check this link
https://info.benswap.cash/pair/0xc1a3bb21dd3bfff9637c4039ff42d08ca497f512

**Comment by webeli** [comment]
@SankarSrinivasan1 still too low liquidity (0.286619 BCH) in the pool. Our system only pulls data from BCH pools with liquidity higher than 0.5 BCH. Please read instructions: https://github.com/MarketCap-Cash/SmartBCH-Token-List

**Comment by webeli** [comment]
No answer in 7 days, closing, please reopen when you have added liquidity.
