### ISSUE TITLE
INSERT TOKEN NAME

### ISSUE THREAD

**Issue by catkingking** [MarketCap-Cash/SmartBCH-Token-List#164]
{
  "name": "catking",
  "desc": "Used for rewards and tips",
  "address": "0xebf8882c3b06f2a776c3c1e29dc9a14410326a8e",
  "symbol": "catking",
  "image": "link to image",
  "websites": ["],
  "telegram": https://t.me/catkingtg"",
  "twitter": "...",
  "discord": "...",
  "github": "catkingking"
}

**Comment by webeli** [comment]
Please fill in more information in the object above (website, image etc).

**Comment by webeli** [comment]
No answer in 15 days, closing this. Please reopen if still relevant.
