### ISSUE TITLE
Please List lawUSD

### ISSUE THREAD

**Issue by Sh11thead** [MarketCap-Cash/SmartBCH-Token-List#167]
{
  "name": "LAW US Dollar",
  "desc": "stable coin of LAW Ecosystem",
  "address": "0xe1e655be6f50344e6dd708c27bd8d66492d6ecaf",
  "symbol": "lawUSD",
  "image": "https://assets.benswap.cash/tokens/0xE1E655BE6F50344e6dd708c27BD8D66492d6ecAf.png",
  "websites": ["https://blockng.money/"],
  "telegram": "https://t.me/BlockNGGlobal",
  "twitter": "https://twitter.com/BlockngO/",
  "github": "https://github.com/BlockNG-Foundation"
}

**Comment by webeli** [comment]
Will add on Friday.

**Comment by webeli** [comment]
Added.
