### ISSUE TITLE
WaterLoan

### ISSUE THREAD

**Issue by marktti** [MarketCap-Cash/SmartBCH-Token-List#168]
{
  "name": "WaterLoan",
  "desc": "WaterLoan is the first lending platform on SmartBCH. Lending projects are generally the leading projects of the public chain, which are of great significance in the public chain. For various mainstream assets on SmartBCH, deposits in WaterLoan can get deposit interest, and you can get additional mining rewards. This article introduces how to mine WAT on the SmartBCH chain.",
  "address": "0x355bf937d42dd19ee60f730d505b0ac03b03e2ae",
  "symbol": "WAT",
  "image": "not yet",
  "websites": ["https://waterloan.finance/"],
  "telegram": "https://t.me/waterloan_official",
  "twitter": "https://twitter.com/realwaterloan",
  "discord": "not yet",
  "github": "https://github.com/waterloan"
}

**Comment by webeli** [comment]
Will add on Friday.

**Comment by bibodeng** [comment]
here is Token logo image: https://raw.githubusercontent.com/IFWallet/csc_tokens/main/logo/0x355bf937D42dd19eE60f730D505B0aC03B03e2ae/logo.png

**Comment by webeli** [comment]
Added.
