### ISSUE TITLE
EMBERSWAP

### ISSUE THREAD

**Issue by marktti** [MarketCap-Cash/SmartBCH-Token-List#169]
{
  "name": "EmberSwap",
  "desc": "EmberSwap is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the smartBCH Network. The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
  "address": "0x6BAbf5277849265b6738e75AEC43AEfdde0Ce88D",
  "symbol": "EMBER",
  "image": "https://github.com/emberswap/assets/blob/a532714908d01040199c84bb8f175e6eeb65bfc7/blockchains/smartbch/assets/EMBER%20ADDRESSE/logo.png",
  "websites": "https://emberswap.com/",
  "telegram": "https://t.me/IncinerateOfficial",
  "twitter": "https://twitter.com/EmberSwapDEX",
  "discord": "https://discord.com/invite/x3TsF9MBrq",
  "github": "https://github.com/emberswap"
}

**Comment by webeli** [comment]
Will integrate EmberSwap on Friday 25/2.

Would love it if BCHPete could add a PR. Also is there an SDK for EmberSwap?

**Comment by bchpete** [comment]
Hey Webeli! Just added SDK for EmberSwap here https://github.com/emberswap/emberswap-sdk

**Comment by marktti** [comment]
Tks guys! Let’s push our SmartBCH!

**Comment by webeli** [comment]
@bchpete great! :)

But please update to the correct `FACTORY_ADDRESS` and `INIT_CODE_HASH` for the SDK.

**Comment by webeli** [comment]
Integrated.
