### ISSUE TITLE
for delisting 'mcash'

### ISSUE THREAD

**Issue by istmeprincess** [MarketCap-Cash/SmartBCH-Token-List#17]
please delist token so called 'mcash' they stole so many persons money and ran away with liquidity, even my friends are too sad about it you may do that kindly.
Contract Address: '0x778C1c04D68c74FfdECBc0950d51033699c8Eb0B'
we must not have those rugpulled tokens here, thankyou.

**Comment by webeli** [comment]
Agreed, removed.
