### ISSUE TITLE
Update Token (EVE)

### ISSUE THREAD

**Issue by PokerJ0k3r** [MarketCap-Cash/SmartBCH-Token-List#172]
Add any update here.
Twitter[   ](https://twitter.com/EVEcoin_info)
EVE smartBCH Evolution Proposal 20. A Layer 2 EVM & Web3 SEP-20 token for dApps, DeFi & DeX on smartBCH.

**Comment by PokerJ0k3r** [comment]
https://twitter.com/EVEcoin_info

**Comment by PokerJ0k3r** [comment]
please update my twitter and project description. thank you for all your help as always sir

**Comment by webeli** [comment]
I've updated the Twitter, but the description is very confusing, not sure what it means. Is EVE an Layer 2 EVM? or a DEX? Closing for now. Please open with if you still want the description to be updated.

**Comment by PokerJ0k3r** [comment]
Thankyou for updating twitters. EvE's new project description here please. EVE's purpose is H.E.A.L.Supporting Humanity, Earth, Animals & Living organisms. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: webeli ***@***.***> Date: 3/19/22  5:37 AM  (GMT-08:00) To: MarketCap-Cash/SmartBCH-Token-List ***@***.***> Cc: PokerJ0k3r ***@***.***>, Author ***@***.***> Subject: Re: [MarketCap-Cash/SmartBCH-Token-List] Update Token (EVE) (Issue #172) 
I've updated the Twitter, but the description is very confusing, not sure what it means. Is EVE an Layer 2 EVM? or a DEX? Closing for now. Please open with if you still want the description to be updated.
