### ISSUE TITLE
BLUE

### ISSUE THREAD

**Issue by Bluemoney14** [MarketCap-Cash/SmartBCH-Token-List#174]
{
  "name": "Bluecoin",
  "desc": "BLUE is a SEP-20 token developed on SmartBCH created by me to show that anyone can create a token/project and teach them the whole process of it",
  "address": "0x757b6A3F53323B6359310749BB9C0F5f3aEE1224",
  "symbol": "BLUE",
  "image": "https://ibb.co/WWrLJCC",
  "websites": ["bit.ly/TradeBLUE"],
  "telegram": "https://t.me/+aqo11IM5Kno0ZjJh",
  }

**Comment by webeli** [comment]
Is there liquidity?

**Comment by Bluemoney14** [comment]
yes sir, the liquidity is on benswap,cash
I share you the hash of the transaction where I add 0.52 BCH of liquidity 
https://www.smartscan.cash/transaction/0x0b0877028367fba5ada4a349dd83c13896cbb908f9595a628c22989ae4b21712

liquidity's picture today
https://ibb.co/XC9YYct

I look forward to your positive response!

**Comment by webeli** [comment]
Added, but please update the website, link to a DEX is not allowed.

**Comment by Bluemoney14** [comment]
oh sorry, i will update, thanks sir ^^
