### ISSUE TITLE
Hype Mate 

### ISSUE THREAD

**Issue by imranpstu14** [MarketCap-Cash/SmartBCH-Token-List#175]
{
  "name": "HypeMate",
  "desc": "Hype$ is a MEME Token on SmartBCH. You can also call it a charity token because it has slightly a different vision to stand by helpless children. It also aims to bring excitement to the SmartBCH chain  and it also dreams to attract more people towards BCH, to  try to bring more influencers on BCH platform, to spread SmartBCH all over for the welfare of BCH.",
  "address": "0x82e45351f76b1ffc10de2a979e327466140c6b35",
  "symbol": "HYPE",
  "image": "https://ibb.co/cLPvcVL",
  "websites": ["https://hypemate.cash/"],
  "telegram": "https://t.me/Hype_Mate",
  "twitter": "https://mobile.twitter.com/hype_mate",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
[imranpstu14](https://github.com/imranpstu14) is it OK for you to use the symbol Hype / Hypes? We currently don't support special characters.

**Comment by imranpstu14** [comment]
I understand. "HYPE" will be ok for us. Now you can list.

**Comment by webeli** [comment]
[imranpstu14](https://github.com/imranpstu14) Will add this when you have https on your website.

**Comment by imranpstu14** [comment]
"https" done. I think now everything is alright for listing.

**Comment by HypeMate** [comment]
https://hypemate.cash/

**Comment by webeli** [comment]
Added.
