### ISSUE TITLE
JOOST

### ISSUE THREAD

**Issue by nathswerve** [MarketCap-Cash/SmartBCH-Token-List#177]
{
  "name": "Joost.energy",
  "desc": ".Tokensing Renewable Energy
![J Icon Joost mistswap](https://user-images.githubusercontent.com/57454965/158878342-0babb3f4-c500-414e-8d85-56e4ebf2d6ba.png)
",
  "address": "0x387122d80A642581E5AD620696a37b98BB9272e7",
  "symbol": "JOOST",
  "image": "[link to image](https://github.com/nathswerve/joost.energy/commit/b2674fdcbfa3e927abbfff362433b86b806de34b)",
  "websites": ["https://joost.energy"],
  "telegram": "t.me/joostchat",
  "twitter": "twitter.com/joostenergy",
  "discord": "...",
  "github": "[.](https://github.com/nathswerve/joost.energy)"
}

**Comment by webeli** [comment]
Added.
