### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by HyperCashSbch** [MarketCap-Cash/SmartBCH-Token-List#179]
{
  "name": "Hyper",
  "desc": "With collecting HYPER tokens you are ready to invest in the SBCH Network! Hyper holders are incentivized to stake their tokens to secure HyperCash, while receiving a reward in return.",
  "address": "0x4aE8Dd5f8AA8F73Cf53a7Ad9187C67d5eaA5B2E1",
  "symbol": "Hyper",
  "image": "[link to image](https://staking.hypercash.site/images/logo2.png)",
  "websites": ["https://hypercash.site"],
  "telegram": "https://t.me/hypercash_sbch",
  "twitter": "https://twitter.com/HyperCashSbch",
  "discord": "...",
  "github": "https://github.com/HyperCashSbch"
}

**Comment by webeli** [comment]
Added, will show up if BCH POOL liquidity is more than 1 BCH on any DEX.
