### ISSUE TITLE
please remove (suspend token for few days)

### ISSUE THREAD

**Issue by istmeprincess** [MarketCap-Cash/SmartBCH-Token-List#18]
![Screenshot_2021-09-22-16-35-19-51_5f48d69e3d30a093162f7e0ee7d45862](https://user-images.githubusercontent.com/88629463/134332889-9da2a2dd-7ed5-41b4-9f1c-84be5df4d2ad.jpg)

hello i am princess here, 
i am here for suspending a token for few weeks if possible because of rude response and direct attack on fair contract, 
that's not allowed to target fair contract as , on liquidity basis, yes we were 1,400$+ before but we are at less then 300$ because of paper hands that exists in our community, but that's not a good way to directly attack on community that is just passing a week of being listed and worked on smartBCH chain, they deserve some punishment so they don't attack fair contracts from next time, please remove them for atleast 'a week' because of that mess, @webeli regards, CandyManFoundation.

**Comment by istmeprincess** [comment]
Token ID: '0x7ebeadb95724a006afaf2f1f051b13f4ebebf711'

**Comment by webeli** [comment]
There's still liquidity for this coin, are you the creator?
