### ISSUE TITLE
Update Token (EVE update to Expected Value 4 Earth) 

### ISSUE THREAD

**Issue by PokerJ0k3r** [MarketCap-Cash/SmartBCH-Token-List#180]
previously named Expected Value in Entropy. i Would like MarketCap.cash to update EVE's Listing Title to Expected Value 4 Earth. as a description. H.E.A.L. Humanity, Earth, Animals & Living Organisms. Our Goal is to turn the H.E.A.L.'s Negative Expectations into a Positive with Environmental Change.

**Comment by PokerJ0k3r** [comment]
Expected Value 4 Earth. A token that stands for Environmental Change. Our Focus is H.E.A.L. Humanity, Earth, Animals & all other Lifeforms.

**Comment by PokerJ0k3r** [comment]
This 1 is Final.
Expected Value for Earth is a Non-Profit Token to support and Heal Humanity, Earth, Animals & all Living Organisms.

**Comment by PokerJ0k3r** [comment]
Expected Value for Earth

**Comment by webeli** [comment]
Update
