### ISSUE TITLE
Update Token (Expected Value for Earth)

### ISSUE THREAD

**Issue by PokerJ0k3r** [MarketCap-Cash/SmartBCH-Token-List#183]
twitter- https://twitter.com/EV4Earth
website - https://www.ev4earth.cash/

Expected Value for Earth is a Non-Profit with a holistic approach to a sustainable future for Humanity, Earth, Animals & all other Lifeforms through environmental change.

Also, i tipped you some EVE tokens to your wallet / Thank you

**Comment by PokerJ0k3r** [comment]
twitter- https://twitter.com/EV4Earth
website - https://www.ev4earth.cash/

Expected Value for Earth (EVE) is a Non-Profit Organization focused on improving Human Ecological relationships with Animals & all Living Organisms (HEAL).

**Comment by PokerJ0k3r** [comment]
twitter- https://twitter.com/EV4Earth
website - https://www.ev4earth.cash/

Expected Value for Earth (EVE) is a Non-Profit Organization focused on improving Human ecological relationships with Earth, Animals & all Living Organisms (HEAL).

**Comment by PokerJ0k3r** [comment]
twitter- https://twitter.com/EV4Earth
website - https://www.ev4earth.org/

Expected Value for Earth is a Non-Profit Organization focused on Human ecological relationships with Earth, Animals & all Living Organisms.

**Comment by webeli** [comment]
Updated.
