### ISSUE TITLE
DCC - Decentralized Cooperation & Collaboration

### ISSUE THREAD

**Issue by clixmoney** [MarketCap-Cash/SmartBCH-Token-List#185]
{
  "name": "Decentralized Cooperation & Collaboration",
  "desc": "The token is to support collaborations on bitcoin cash network and then to collaborate with all crypto community.",
  "address": "0x953C198399ed395111199FF01806ca3CEaa6326f",
  "symbol": "DCC",
  "image": "[link to image](https://www.linkpicture.com/q/1111_7.png)",
  "websites": ["https://hive.blog/hive-177976/@clixmoney/dccoin-is-created-the-total-is-1-million"],
  "telegram": "cnycik",
  "twitter": "clixmoney1",
  "discord": "https://discord.com/invite/YhfG778yCw",
}

**Comment by clixmoney** [comment]
I'm sorry that I didn't add liquidity yet. I'm just learning about all this and I noticed the information about liquidity later. I don't know if I will add liquidity on one dex, is that mean having the token in all of them after ?

**Comment by webeli** [comment]
You only need liquidity in one dex, our system will find it, let us know when it's done.

**Comment by webeli** [comment]
No answer in 12 days, closing.
