### ISSUE TITLE
Update Token (Friend) to (Wyvernegg)

### ISSUE THREAD

**Issue by ag076810** [MarketCap-Cash/SmartBCH-Token-List#186]
Hi webeli ,

WyvernEgg Studio was formerly known as Friend DAO. We have adjusted white paper, tokenomic and website to fit the new business model,Please help us update token information,thanks

{
"name": "Wyvernegg",
"desc": "WyvernEgg Studio was formerly known as Friend DAO. We have adjusted white paper, tokenomic and website to fit the new business model. WyvernEgg Studio is dedicated to Dapp development and high quality NFT design. We are looking forward to providing SmartBCH with more diverse and interesting feature.",
"address": "0x7ccb2b0012cb821b908d3db353db922a1a71e963",
"symbol": "WVE",
"image": "https://wyvernegg.com/imgs/logo_small.png",
"websites": "https://wyvernegg.com/",
"telegram": ".https://t.me/wyvernegg",
"twitter": "https://twitter.com/wyverneggstudio",
}

“Which DEX is your liquidity on : https://analytics.mistswap.fi/pairs/0xad2b92011e279a5f7de36faa393ebbeee2b622e7

**Comment by webeli** [comment]
This should be a new listing.
