### ISSUE TITLE
Please Add Sep20 Token "$bunny"

### ISSUE THREAD

**Issue by AlvinBch** [MarketCap-Cash/SmartBCH-Token-List#19]
{
"name": "BunnyBCH",
"address":"0x43839580d15b3cea21b9523e3be4053ea90e61ad",
"symbol": "$bunny",
"image": "https://imgshare.io/image/untitled1-20210923191223.pQqPVj"
"website": "N/A",
"telegram": "https://t.me/bunnybch",
"twitter": "https://twitter.com/BunnyBCH_?s=09"
}

**Comment by webeli** [comment]
Very low liquidity.
