### ISSUE TITLE
Global Transaction Payment Solution

### ISSUE THREAD

**Issue by GtpsFinance** [MarketCap-Cash/SmartBCH-Token-List#193]
{
  "name": "Global Transaction Payment Solution",
  "desc": "....",
  "address": "0x9427A2a738AffBc5880F0646b5251069c022e525",
  "symbol": "GTPS",
  "image": "[link to image](https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/225x225GTPS.png?ver=1649021019248)",
  "websites": ["https://gtps.finance/"],
  "telegram": "https://t.me/joinusatgtpsfinance",
  "twitter": "[.](https://twitter.com/GtpsFinance)",
  "discord": "...",
  "github": "(https://github.com/GtpsFinance?tab=repositories)"
}

**Comment by webeli** [comment]
What connection does this project have to: https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/195

**Comment by webeli** [comment]
No answer in 12 days, closing.
