### ISSUE TITLE
Gtps.Finance

### ISSUE THREAD

**Issue by GtpsFinance** [MarketCap-Cash/SmartBCH-Token-List#194]
{
  "name": "Gtps.Finance",
  "desc": "....",
  "address": "0xA47d18B6409bDed0cbCc1AaCB6036543fB6B2b85",
  "symbol": "GFI",
  "image": "[link to image](https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/GtpsFinance225x225.png?ver=1649021019248)",
  "websites": ["https://gtps.finance/"],
  "telegram": "https://t.me/jpoinusatgtpsfinance",
  "twitter": "(https://twitter.com/GtpsFinance)", 
  "github": "(https://github.com/GtpsFinance?tab=repositories)"

**Comment by webeli** [comment]
Which connections does these project have: https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/195 https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/194 https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/193

**Comment by GtpsFinance** [comment]
its token deployed on smartBCH add to token list
________________________________

**Comment by webeli** [comment]
Please elaborate, not sure what the connection is between the three projects you applied for.
