### ISSUE TITLE
Ultimatalioniscoin

### ISSUE THREAD

**Issue by GtpsFinance** [MarketCap-Cash/SmartBCH-Token-List#195]
{
  "name": "Ultimatalioniscoin",
  "desc": "....",
  "address": "0x0524aCEb3ebf12d4F24DEc29B078ca92D848a559",
  "symbol": "ULC",
  "image": "[link to image](https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/Ultimatalioniscoin225x225.png?ver=1649021019249)",
  "websites": ["https://gtps.finance/"],
  "telegram": "https://t.me/joinusatgtpsfinance",
  "twitter": "https://twitter.com/GtpsFinance",
  "discord": "...",
  "github": "(https://github.com/GtpsFinance?tab=repositories)"
}

**Comment by webeli** [comment]
Please add a description.

**Comment by webeli** [comment]
What connection does this project have to: https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/193

**Comment by webeli** [comment]
No answer in 12 days, closing.

**Comment by GtpsFinance** [comment]
sorry haven't checked my messages


________________________________
