### ISSUE TITLE
SSS

### ISSUE THREAD

**Issue by Tellbird** [MarketCap-Cash/SmartBCH-Token-List#196]
{
  "name": "SSS",
  "desc": "The first algorithmic token pegged to $BCH on the SmartBCH network.",
  "address": "0x9c106Dd7F8d3f873779696654d55e79ebC89bA7A",
  "symbol": "SSS",
  "image": "https://raw.githubusercontent.com/SSSCASH/assets/main/sss_logo.png",
  "websites": ["https://www.sss.cash/"],
  "telegram": "https://t.me/ssscash",
  "twitter": "https://twitter.com/3scash",
  "discord": "",
  "github": "https://github.com/SSSCASH"
}

**Comment by Tellbird** [comment]
Dear administrator, we have been added to the whitelist on benswap and have started trading. The address is as follows, I hope you can pass, thank you.
https://dex.benswap.cash/#/swap?outputCurrency=0x9c106Dd7F8d3f873779696654d55e79ebC89bA7A

**Comment by webeli** [comment]
Added.
