### ISSUE TITLE
SSHARE

### ISSUE THREAD

**Issue by Tellbird** [MarketCap-Cash/SmartBCH-Token-List#197]
{
  "name": "SSHARE",
  "desc": "SSHARE holders have voting rights (governance) on proposals to improve the protocol and future use cases within the SSS,CASH ecosystem.",
  "address": "0x780fe9a1a6498bA2C08D739872Eddf7B061EBbeC",
  "symbol": "SSHARE",
  "image": "https://raw.githubusercontent.com/SSSCASH/assets/main/sshare_logo.png",
  "websites": ["https://www.sss.cash/"],
  "telegram": "https://t.me/ssscash",
  "twitter": "https://twitter.com/3scash",
  "discord": "...",
  "github": "https://github.com/ssscash"
}

**Comment by webeli** [comment]
Added.
