### ISSUE TITLE
SBOND

### ISSUE THREAD

**Issue by Tellbird** [MarketCap-Cash/SmartBCH-Token-List#198]
{
  "name": "SBOND",
  "desc": "SBOND main job is to help incentivize changes in SSS supply during an epoch contraction period.",
  "address": "0xFD07C46121F5c621784146731D673B32e0aBDA6B",
  "symbol": "SBOND",
  "image": "https://raw.githubusercontent.com/SSSCASH/assets/main/sbond_logo.png",
  "websites": ["https://www.sss.cash/"],
  "telegram": "https://t.me/ssscash",
  "twitter": "https://twitter.com/3scash",
  "discord": "...",
  "github": "https://github.com/ssscash"
}

**Comment by webeli** [comment]
Added.
