### ISSUE TITLE
HyperCash

### ISSUE THREAD

**Issue by HyperCashSbch** [MarketCap-Cash/SmartBCH-Token-List#199]
{
  "name": "HyperCash",
  "desc": "Decentralized Platform on SBCH",
  "address": "0x60Cb3A6ECF7EA66d553188B180F587C38Bf5caB2",
  "symbol": "HCash",
  "image": "[link to image](https://ibb.co/sHzL269)",
  "websites": ["https://hypercash.site/"],
  "telegram": "https://t.me/hypercash_sbch",
  "twitter": "https://twitter.com/HyperCashSbch",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
Which connections does this project have to HYPER?

**Comment by HyperCashSbch** [comment]
Yes, the reward token for Hyper. It's all managed by the same developer.
Thanks!

**Comment by webeli** [comment]
Do you have liquidity on any DEX?

**Comment by webeli** [comment]
No answer in 11 days, closing.
