### ISSUE TITLE
Please add Sep-20 token BTS.Finance

### ISSUE THREAD

**Issue by yoshigrando** [MarketCap-Cash/SmartBCH-Token-List#20]
{
"name": "BTS.Finance",
"address": "0xa2EC49d721dB366Da7311232103EEadDD168B890",
"symbol": "BTS",
"image": "https://imgshare.io/image/pQTB3Z",
"website": "N/A",
"telegram": "https://t.me/btsfinance",
"twitter": "N/A"
}

**Comment by webeli** [comment]
Very low liquidity.
