### ISSUE TITLE
Africa Unite 

### ISSUE THREAD

**Issue by africaunitebch** [MarketCap-Cash/SmartBCH-Token-List#200]
{
  "name": "Africa Unite",
  "desc": "Africa Unite (MartinB) aims at preaching unification, human development/use case for other token in totality helping Bitcoin Cash to achieve its mission.",
  "address": "0x4EA4A00E15B9E8FeE27eB6156a865525083e9F71",
  "symbol": "MartinB",
  "image": "https://raw.githubusercontent.com/africaunitebch/africaunitebch.github.io/main/assets/images/logo.png",
  "websites": ["https://marketcap.cash/africaunitebch.png"],
  "telegram": "https://t.me/Africaunitebch",
  "twitter": "https://twitter.com/AfricaUniteBCH",
  "github": "https://github.com/africaunitebch"
}

**Comment by webeli** [comment]
We don't support special characters in the symbol key, please change.

**Comment by africaunitebch** [comment]
Please see updated version. Thank you :)

**Comment by webeli** [comment]
Do you have liquidity on any DEX?

**Comment by africaunitebch** [comment]
> Do you have liquidity on any DEX?

Yes, we are listed in tangoswap and currently have 2x farm there.

**Comment by webeli** [comment]
Added.
