### ISSUE TITLE
BCHTOWNS

### ISSUE THREAD

**Issue by ghost** [MarketCap-Cash/SmartBCH-Token-List#201]
{
  "name": "BCHTOWNS",
  "desc": "An upcoming 4X Strategy/Town Building/Resource management game",
  "address": "0x0cE452619A3B3aA4B648760FAc97e1896534BCAd",
  "symbol": "TOWN",
  "image": "https://raw.githubusercontent.com/bchtowns/assets/b405659258932ee30eb1e0cb22e4f97add0b4075/blockchains/smartbch/assets/0x0cE452619A3B3aA4B648760FAc97e1896534BCAd/logo.png",
  "websites": ["https://bchtowns.com", "http://play.bchtowns.com/"],
  "telegram": "https://t.me/bchtowns",
  "twitter": "https://twitter.com/bchtowns",
  "github": "https://github.com/bchtowns"
}

**Comment by webeli** [comment]
Does this project have any liquidity on a DEX?

**Comment by webeli** [comment]
Closing.
