### ISSUE TITLE
Please help to Integration LawSwap

### ISSUE THREAD

**Issue by BlockNG** [MarketCap-Cash/SmartBCH-Token-List#203]
Hi, 

The current BlockNG protocol has opened the migration of liquidity to LawSwap.

Here is our LawSwap SDK.

https://github.com/BlockNG-Foundation/blockng-swap-sdk

We hope you can help integrate LawSwap into MarketCap.cash .

If there is anything else we can provide, please let us know and we will be happy to assist

**Comment by webeli** [comment]
Ofcourse @BlockNG, thanks for the SDK, will do it asap.

**Comment by webeli** [comment]
Done.

**Comment by BlockNG** [comment]
Thanks !
