### ISSUE TITLE
LAD$ Listing Request

### ISSUE THREAD

**Issue by jackhbgs** [MarketCap-Cash/SmartBCH-Token-List#204]
{
  "name": "LAD$",
  "desc": "Be A Forgotten Lad Holder To Earn.",
  "address": "0xB34cBd2821B4e2F2E1223D08A11258076746F886",
  "symbol": "LAD$",
  "image": "link to image",
  "websites": ["https://lads.cash/"],
  "telegram": "https://t.me/ladsnft",
  "twitter": "https://twitter.com/LadNFTs",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
Do you have liquidity on a DEX?

**Comment by webeli** [comment]
No answer in 10 days, closing.
