### ISSUE TITLE
Goblins BCH

### ISSUE THREAD

**Issue by trankuilized** [MarketCap-Cash/SmartBCH-Token-List#206]
{
   "gBCH": {
    "name": "Goblins BCH",
    "desc": "First elastic supply token on SmartBCH that tracks the price of BCH and adds POL for market participants of Goblins Cash",
    "address": "0x009dC89aC501a62C4FaaF7196aeE90CF79B6fC7c",
    "symbol": "gBCH",
    "image": "https://main.dfd.cash/static/media/GBCH.787b2410.png",
    "websites": ["https://goblins.cash"],
    "telegram": "https://t.me/GoblinsCash",
    "twitter": "https://twitter.com/GoblinsCash"
}

**Comment by webeli** [comment]
Added.

**Comment by trankuilized** [comment]
you rock. ty!
