### ISSUE TITLE
Spacebux

### ISSUE THREAD

**Issue by Spacebuxcrypto** [MarketCap-Cash/SmartBCH-Token-List#209]
{
  "name": "Spacebux",
  "desc": "Spacebux is a social utility token used for community rewards, giveaways and transactions.",
  "address": "0x83Ef1F5630a16eA56c137cdA5A24f8BcfFa1B158",
  "symbol": "SBX",
  "image": "https://spacebux.info/spacebuxlogo.png",
  "websites": ["https://spacebux.info/"],
  "telegram": "t.me/spacebux",
  "twitter": "https://twitter.com/SpacebuxCrypto",
  "discord": "...",
  "github": "..."
}

**Comment by webeli** [comment]
Do you have liquidity on any DEX?

**Comment by webeli** [comment]
No answer in 11 days, closing.
