### ISSUE TITLE
Integrate Official HONK DEX

### ISSUE THREAD

**Issue by 3even** [MarketCap-Cash/SmartBCH-Token-List#211]
Hi @webeli 

Could you please integrate the official HONK DEX into MarketCap.cash.

DEX Url:
[defi.honk.cash](https://defi.honk.cash/)

DEX Repo:
[https://github.com/honk-world/honkswap](https://github.com/honk-world/honkswap)

DEX SDK:
[https://github.com/honk-world/honkswap-sdk](https://github.com/honk-world/honkswap-sdk)

Let us know if there is anything you need. Thank you!

**Comment by webeli** [comment]
Very cool, will integrate it when you have more liquidity, it's very low now.

**Comment by 3even** [comment]
@webeli Thanks for the response. What would be the minimum liquidity threshold for you to consider inclusion?

**Comment by webeli** [comment]
@3even not sure tbh, a couple of tokens on your DEX with liquidity above 20-30 BCH maybe.
