### ISSUE TITLE
NFTC

### ISSUE THREAD

**Issue by NftClubCash** [MarketCap-Cash/SmartBCH-Token-List#212]
{
  "name": "NFT Club Token",
  "desc": "The main token of the NFTClub. With this token it is possible to participate in our ecosystem. It is meant for many usecases and we are constantly working on releasing new usecases to give our users the best experience.",
  "address": "0x8dd87b3f50bE9C6Ac5EC08458803843F0D294B3d",
  "symbol": "NFTC",
  "image": "https://raw.githubusercontent.com/NftClubCash/logos/main/nftclogo.png",
  "websites": [ "https://nftclub.cash", "https://app.nftclub.cash"],
  "telegram": "https://t.me/NFTClubOfficial",
  "twitter": "https://twitter.com/PixelGuyClub1",
  "discord": "https://discord.gg/8zqzw8zs",
  "github": "https://github.com/NftClubCash"
}

**Comment by NftClubCash** [comment]
More than 40 BCH of liquidity has been added on MistSwap.

**Comment by webeli** [comment]
Added.
