### ISSUE TITLE
Integrate Verse DEX liquidity

### ISSUE THREAD

**Issue by leonidasmark** [MarketCap-Cash/SmartBCH-Token-List#213]
Please add Verse as a liquidity provider for all the tokens. It is slowly getting more and more liquidity and is currently sitting at $1.2 million

https://verse.bitcoin.com/

**Comment by webeli** [comment]
@leonidasmark ofcourse, can you give me a link to their SDK?

**Comment by vm06007** [comment]
@webeli SDK? I guess you're referring to graphQL API? https://analytics-dex.api.bitcoin.com/subgraphs/name/verse/exchange
let me know if this is what you're looking for 🙌

**Comment by webeli** [comment]
Closing, no update.
