### ISSUE TITLE
Please add SEP-20 token "LAW"

### ISSUE THREAD

**Issue by BlockNG** [MarketCap-Cash/SmartBCH-Token-List#22]
{
"name": "LAWTOKEN",
"address": "0x0b00366fBF7037E9d75E4A569ab27dAB84759302",
"symbol": "LAW",
"image": "https://blockng.money/favicon.svg",
"website": "https://blockng.money/#/",
"telegram": "https://t.me/BlockNGGlobal"
}

**Comment by BlockNG** [comment]
Thank you!

**Comment by webeli** [comment]
Done.

**Comment by BlockNG** [comment]
Great project!
