### ISSUE TITLE
Add token MIST

### ISSUE THREAD

**Issue by kratatomi** [MarketCap-Cash/SmartBCH-Token-List#23]
{
"name": "MIST",
"address": "0x5fa664f69c2a4a3ec94fac3cbf7049bd9ca73129",
"symbol": "MIST",
"image": "https://app.mistswap.fi/_next/image?url=%2Fimages%2Ftokens%2Fxmist-square.jpg&w=48&q=75",
"website": "https://app.mistswap.fi/",
"discord": "https://discord.gg/xFTnQEzu9T",
"twitter": "https://twitter.com/mistswapdex"
}

AFAIK there's not telegram group but a discord one.

**Comment by webeli** [comment]
Will add it asap (need to implement MistSwap SDK first).

**Comment by webeli** [comment]
Added.
