### ISSUE TITLE
Please add SEP-20 token "$HAM"

### ISSUE THREAD

**Issue by ElDoradoTG** [MarketCap-Cash/SmartBCH-Token-List#3]
{
"name": "HAM Token",
"address": "0x252fd94f3Fb53D3D62F4FEc708501ACd59A57e52",
"symbol": "HAM",
"image": "https://imgshare.io/images/2021/09/09/HAM_Icon_with-BCH__SLP__KRON_Logo1017x1017.png",
"website": "https://linktr.ee/The_HAM_Token",
"telegram": "https://t.me/HAM_Token_Chat",
"twitter": "@HAM_Token"
}

**Comment by webeli** [comment]
Added.
