### ISSUE TITLE
Please add DOGEBCH

### ISSUE THREAD

**Issue by montemurroPaolo** [MarketCap-Cash/SmartBCH-Token-List#30]
{
"name": "DOGEBCH",
"desc": "No roadmap. No use case. No rug. Just DOGE on BCH",
"address": "0x741746C2Cf4117730d7f087e8492dF595b4fd283",
"symbol": "DOGE",
"image": "https://dogebch.com/images/pngegg_compressed.png",
"website": "www.dogebch.com",
"telegram": "https://t.me/joinchat/m6xNt45ipR8zYjY0",
"twitter": "..."
}

**Comment by istmeprincess** [comment]
13 bch in liquidity, doesnt mean that it have 50$k in liquidity lol
