### ISSUE TITLE
Please Add MrUSD

### ISSUE THREAD

**Issue by iammultiman** [MarketCap-Cash/SmartBCH-Token-List#32]
{
"name": "MrUSD",
"desc": "MoTA Remit Universal Stable Digital Token",
"address": "0x048a4811d30089b5AA86e2E711A6A4aa67dbe275",
"symbol": "MrUSD",
"image": "https://motaglobal.club/online/wp-content/uploads/2021/09/Mota-USD3b_trans-300x240.png",
"website": "https://motaglobal.club/online/",
"telegram": "https://t.me/motaglobal",
"twitter": "https://twitter.com/MotaGlobal"
}

**Comment by webeli** [comment]
Please add correct address.

**Comment by iammultiman** [comment]
> Please add correct address.

Address updated to 0x048a4811d30089b5AA86e2E711A6A4aa67dbe275

Thanks

**Comment by webeli** [comment]
Needs more liquidity before we can add it, can see that there's liquidity on MistSwap and Benswap, but its very low.

**Comment by iammultiman** [comment]
> Needs more liquidity before we can add it, can see that there's liquidity on MistSwap and Benswap, but its very low.

More liquidity added for MrUSD

**Comment by webeli** [comment]
Added.
