### ISSUE TITLE
PLEASE ADD EROS

### ISSUE THREAD

**Issue by EROSAGON** [MarketCap-Cash/SmartBCH-Token-List#34]
{
"name": "EROS",
"desc": "a platform where sport betting will be taken place",
"address": "0xF3475035C1C3e008Fb52C57ed7227aD572b4380E",
"symbol": "EROS",
"image": "
![image](https://user-images.githubusercontent.com/92664915/137616622-b3860a42-7943-4426-b4cf-9bc92f2c73e0.png)
",
"website": "https://Eronsxagon.com",
"telegram": "https://t.me/ErosBCH",
"twitter": "https://twitter.com/erosxagon"
}

**Comment by webeli** [comment]
Added.
