### ISSUE TITLE
Please add NomadCoin, liquidity added on MistSwap

### ISSUE THREAD

**Issue by nomadghada** [MarketCap-Cash/SmartBCH-Token-List#36]
{
"name": "NomadCoin",
"address": "0xEE1bA4e4C266C7cc071f5de5e6dc90965E608087",
"symbol": "NOMAD",
"image": "https://nomadcoinproject.files.wordpress.com/2021/09/nomad_logo-round.png?w=150",
"website": "https://nomadcoinproject.wordpress.com/",
"read.cash": "https://read.cash/c/nomadcoin-00dd",
"noise.cash": "https://noise.cash/c/nomadcoin-xlpnq67l",
}

**Comment by webeli** [comment]
Need more than 0.05 liquidity on the BCH pair. It's to low now unfortunately.

**Comment by webeli** [comment]
No update for 19 days, closing this issue. Please open a new one with description and where liquidity is added.
