### ISSUE TITLE
Please add SEP-20 token "$WRS"

### ISSUE THREAD

**Issue by ElDoradoTG** [MarketCap-Cash/SmartBCH-Token-List#4]
{
"name": "The Wireless Token",
"address": "0x445B3712A09f8102Dd0c1ffb6B3b0dE4D3B643b7",
"symbol": "$WRS",
"image": "https://imgshare.io/images/2021/09/09/WRS_Icon_circle-croppedwith_White.png",
"website": "https://linktr.ee/The_HAM_Token",
"telegram": "https://t.me/HAM_Token_Chat",
"twitter": "@HAM_Token"
}

**Comment by webeli** [comment]
Added.
