### ISSUE TITLE
KAIJU - Add liquidity on MistSwap > 0.05 BCH Already

### ISSUE THREAD

**Issue by NakamuraTokio** [MarketCap-Cash/SmartBCH-Token-List#47]
{
   "name":     "Kaiju",
   "desc" :     " KaiJu : The Shitcoin Killer, KaiJu is also called the Shitcoin Killer. 
                        We just born to be the No.1 of Shitcoin in this Galaxzy, 
                        After the Shitcoin wars end, the last one stand is KaiJu
      
                        Plan of Kaiju
      
                        SEP 21
                        TEAM'UP
                        Create Team for Kaiju
                        CTO : 芝はゲーマーです (AKA : Kaiju Master)
                        Head of Dev : キット (AKA : Kaiju Nerd)
                        Graphic Design : ナパパット (AKA : Kaiju Art)
                        Transaltor : チャットチャノック (AKA : Kaiju Jelly)
      
                        OCT 21
                        Publish Kaiju Token in SmartBCH <-- Now we're here
                        and Listing in Swap platform maybe MistSwap
                        
                        NOV 21
                        CREATE KAIJU NFT NAMELY : KAIJUCARD
                        and sell all KaijuCard in kaiju.cash via SmartBCH
                        
                        DEC 21
                        PRODUCE THE NFT MARKETPLACE FOR SMARTBCH
                        Everyone can sell Their NFT without any fee from our platform for first 5 NFT,
                         if the user want to sell more than 5 just Subscript us 2$/month
                        
                        FEB 21
                        CREATE KAIJU NFT GAME NAMELY : KAIJU CARD BATTLE ARENA
                        Player can using the KaijuCard to play the game with others, 
                        if you loose in the battle you lose 1 of your card from ypur desk by random to winnerFEB 22",
   "address":   "0x4f909dFE5Daaf94fbd1fD4C2E582F7608C87cd94",
   "symbol":    "KAIJU",
   "image":      "https://kaiju.cash/images/Kaiju_Coin_Icon_BGK.png",
   "website":   "https://kaiju.cash",
   "telegram": "https://t.me/KaiJuTheShitcoinKiller",
   "twitter":     "https://twitter.com/KaijuCash"
}

**Comment by NakamuraTokio** [comment]
Now, we add some liquidity into MistSwap
>> https://app.mistswap.fi/swap?inputCurrency=&outputCurrency=0x4f909dFE5Daaf94fbd1fD4C2E582F7608C87cd94

**Comment by webeli** [comment]
Need more than 0.05 BCH liquidity on MistSwap.

**Comment by NakamuraTokio** [comment]
> Need more than 0.05 BCH liquidity on MistSwap.

Ok, Added

Thank for your support.

**Comment by NakamuraTokio** [comment]
> Need more than 0.05 BCH liquidity on MistSwap.


Sir @webeli  we  already added liquidity in MistSwap (>0.05) already :) 
Hope we list on marketcap soon

Thank for your support.

**Comment by NakamuraTokio** [comment]
@webeli , it still avi to add our coin to your site ?

**Comment by webeli** [comment]
@NakamuraTokio please give us a more detailed description, don't understand what you mean with "a shitcoin killer". Update the description to make it clear for new people what the project is all about.

**Comment by webeli** [comment]
No update in 5 days, closing for now, please reopen when updated with info.
