### ISSUE TITLE
Add Xolos RMZ token to marketcap.cash

### ISSUE THREAD

**Issue by Gutiman18** [MarketCap-Cash/SmartBCH-Token-List#48]
{
"name": "Xolos",
"address": "0x49F9ECF126B6dDF51C731614755508A4674bA7eD",
"symbol": "RMZ",
"image": "https://user-images.githubusercontent.com/68677413/139557529-86e797d1-8ba2-4040-8acd-4344530bd835.png",
"Twitter": "https://twitter.com/xolosramirez1/",
"Telegram": "https://t.me/xolosramirez",
"Website": "https://www.xolosramirez.com/nft-xolos-ramirez/",
"Reddit": "https://www.reddit.com/user/XolosRamirez",
![logo](https://user-images.githubusercontent.com/68677413/139557529-86e797d1-8ba2-4040-8acd-4344530bd835.png)

}

**Comment by Gutiman18** [comment]
Hi Sir @webeli Xolos RMZ ⚡ already has liquidity in Mistswap, AND would love to be added to marketcap.cash list

**Comment by webeli** [comment]
Done.
