### ISSUE TITLE
FlokiBCH Token

### ISSUE THREAD

**Issue by ag076810** [MarketCap-Cash/SmartBCH-Token-List#49]
{
"name": "Floki BCH",
"address": "0x8128b9d0819eb2ec966eeec409122155aa78ad1f",
"symbol": "FlokiBCH",
"image": "https://coinalpha.app/images/coin/1_20210909075425.png",
"twitter": "https://twitter.com/BchFloki",
}

**Comment by ag076810** [comment]
I add 50000 mist liquidity on MistSwap.

**Comment by webeli** [comment]
website?

**Comment by webeli** [comment]
No update for 18 days, closing for now. Please open a new issue with more information about this token, website, description, liquidity etc.
