### ISSUE TITLE
Please add Sep20 Token "$Kitten"

### ISSUE THREAD

**Issue by Denise098** [MarketCap-Cash/SmartBCH-Token-List#5]
{
"name": "CashKitten",
"address": "0x7ebeadb95724a006afaf2f1f051b13f4ebebf711",
"symbol": "$KITTEN",
"image": "https://imgshare.io/image/20210910-033215.puDSl6"
"website": "N/A",
"telegram": "https://t.me/CashKitten_BCH",
"twitter": "https://twitter.com/CashKitten_BCH"
}

**Comment by webeli** [comment]
Added.
