### ISSUE TITLE
Add MoonMoon

### ISSUE THREAD

**Issue by MoonMoonTG** [MarketCap-Cash/SmartBCH-Token-List#50]
{
"name": "MoonMoon",
"address": "0x039Bcd43B18A29aa72CabFe269BA045447C881E4",
"symbol": "MM",
"image": "https://i.gyazo.com/d77c3243caa5112d733ba4979ec51942.png",
"website": "https://moonmoon.dog/",
"telegram": "https://t.me/Moonmoontothemoon",
"twitter": "https://twitter.com/HaiGonnaMoon"
"MistSwap": "https://app.mistswap.fi/swap?inputCurrency=0x039Bcd43B18A29aa72CabFe269BA045447C881E4&outputCurrency=",
}

**Comment by webeli** [comment]
Please open a new issue if this token still should be listed, heard something about a rugpull etc. Need more information, liquidity, description etc.
