### ISSUE TITLE
Request for listing M<ADD Klover Cash>

### ISSUE THREAD

**Issue by Klovercash** [MarketCap-Cash/SmartBCH-Token-List#51]
{
"name": "KLOVERCASH",
"address": "0x66d5fD5f7579a9D332A85c6B24E232f6cDE8F8cd",
"symbol": "KLR",
"image": "
![image](https://user-images.githubusercontent.com/93865148/140643960-bf60ee44-8a4d-448c-816b-fe9efbadf2c8.png)
",
"website": "https://Klovercash.org",
"telegram": "https://t.me/kloverCashBCH",
"twitter": "https://twitter.com/cashklover"
}

**Comment by Klovercash** [comment]
list please

**Comment by webeli** [comment]
On which DEXs do you have liquidity?

**Comment by webeli** [comment]
No update in 5 days, closing for now, please reopen when updated liquidity.
