### ISSUE TITLE
Request for listing MEMA

### ISSUE THREAD

**Issue by 076n00b** [MarketCap-Cash/SmartBCH-Token-List#53]
{
"name": "MEM Arend",
"address": "0x8958A2d2010b88e53B028ad99E4b17169265bfC0",
"symbol": "MEMA",
"image": "https://kapot.ga/wp-content/uploads/2021/11/MEMArendlogo.jpg",
"website":"https://kapot.ga/mem-arend-token/",
}

**Comment by webeli** [comment]
Please add more information, description, social media etc. Where do you have liquidity?

**Comment by webeli** [comment]
No update in 5 days, closing for now, please reopen when updated with info.
