### ISSUE TITLE
Adding RugRugToken

### ISSUE THREAD

**Issue by GodfatherForTokens** [MarketCap-Cash/SmartBCH-Token-List#54]
{
"name": "RugRugToken",
"desc": "A token made during the rug pull of Moon Moon when the person running the entire group, did not actually own the token rights, so the girl who did sold minted token down into his liquidity and got a free 1.5 bch. He took offense to that, and so made rug token to pay back and return the tokens to the group he was running. Ownership burned, original supply stack of owner burned and then bought back when people put in liquidity, now is using it for job purposes. It's a token around moon patterns, increasing value of holding Rug owners, while air dropping tokens for up to a maximum of it's holders stacks. Uses the rug to hire people to help it gain tech, currently looking to a casino. We can't do moon moon anymore, dogs don't do well with rugs.",
"address": "0x2FBd3dDceCd02A95D712C4185aE0eB8C87c4a327",
"symbol": "RUG",
"image": "https://i.imgur.com/Q0PSUy8.jpg",
"website": "Work in progress, looking for good domain names.",
"telegram": "https://t.me/RugRugRedemption",
"twitter": "https://twitter.com/HaiGonnaMoon"
}

**Comment by webeli** [comment]
Please come back (open a new issue) when you have a website and a more clear description of the use case of this token, don't really understand the desc and it's future.
