### ISSUE TITLE
Add New Token

### ISSUE THREAD

**Issue by Ab2thousand3** [MarketCap-Cash/SmartBCH-Token-List#55]
{
"name": "ForXtra",
"desc": "....",
"address": "0xC595672b8eC5F27BB4078a7eF6382fb896aDD8E9",
"symbol": "ForX",
"image": "https://ibb.co/xgggK3s",
"website": "https://forxtra.com/",
"telegram": "....",
"twitter": "..."
}

**Comment by webeli** [comment]
Please update with more information (description, social media, liquidity etc).

**Comment by webeli** [comment]
No update in 5 days, closing for now, please reopen when updated with info.
