### ISSUE TITLE
Add LILY FLOWER 

### ISSUE THREAD

**Issue by LILYFLOWERTOKEN** [MarketCap-Cash/SmartBCH-Token-List#58]
{
"name": "LILY FLOWER",
"desc": "LILY FLOWER (LILY) is a decentralized Token built on the base of the blockchain on SmartBCH (SBCH network) which offers a modulated and modern way of providing benefits to all involved users.
",
"address": "0x5A0C102818d1EE4874d20eE035871bE259E353DD",
"symbol": "LILY",
"image": "https://i.postimg.cc/tCWX32wK/64.png",
"website": "https://medium.com/@lilyflowertoken/lily-flower-token-432a20437b30",
"telegram": "https://t.me/LILYFlowerToken",
"twitter": "https://twitter.com/LilyFlowerToken"
}

**Comment by webeli** [comment]
On which DEXs do you have liquidity?

**Comment by LILYFLOWERTOKEN** [comment]
MistSwap
Check here - https://app.mistswap.fi/swap?inputCurrency=0x5A0C102818d1EE4874d20eE035871bE259E353DD&outputCurrency=

**Comment by webeli** [comment]
To low liquidity.

**Comment by webeli** [comment]
No update in 5 days, closing for now, please reopen when updated liquidity.
