### ISSUE TITLE
Incinerate

### ISSUE THREAD

**Issue by bchpete** [MarketCap-Cash/SmartBCH-Token-List#60]
{
"name": "Incinerate",
"desc": "The Incinerate Protocol is a DeFi Token created with focus on scarcity. Burning, fee distribution and liquidity acquisition.
",
"address": "0x225FCa2A940cd5B18DFb168cD9B7f921C63d7B6E",
"symbol": "FIRE",
"image": "https://incinerate.cash/img/logo.png",
"website": "https://incinerate.cash/",
"telegram": "https://t.me/IncinerateOfficial",
"twitter": "https://twitter.com/Incinerate_cash"
}

**Comment by webeli** [comment]
On which DEXs do you have liquidity?

**Comment by bchpete** [comment]
I don't have any liquidity on any DEXes yet. Pre-sale is planned for 30/11 and plan was to be adding all liquidity from presale to MistSwap afterwards.

**Comment by webeli** [comment]
Let's reopen this when you have liquidity, closing for now.

**Comment by bchpete** [comment]
0x1F354956DE4A7Ed71308225De94a27b35A84EA57 Liquidity has been added on MistSwap, can you reopen now?
