### ISSUE TITLE
New Issue For SEP20 Token Addition

### ISSUE THREAD

**Issue by iammultiman** [MarketCap-Cash/SmartBCH-Token-List#63]
{
"name": "MrUSD",
"desc": "MoTA Remit Universal Stable Digital Token",
"address": "0x048a4811d30089b5AA86e2E711A6A4aa67dbe275",
"symbol": "MrUSD",
"image": "https://motaglobal.club/online/wp-content/uploads/2021/09/Mota-USD3b_trans-300x240.png",
"website": "https://motaglobal.club/online/",
"telegram": "https://t.me/motaglobal",
"twitter": "https://twitter.com/MotaGlobal"
}

Liquidity was added to BCH pair as requested as condition for listing. New issue as old issue to have gone under the radar.

**Comment by webeli** [comment]
Added.
