### ISSUE TITLE
Please Add DAO into the list

### ISSUE THREAD

**Issue by jackhbgs** [MarketCap-Cash/SmartBCH-Token-List#64]
{
"name": "DAO",
"desc": "Decentralized Autonomous Organization",
"address": "0xca0235058985fcc1839e9e37c10900a73c126708",
"symbol": "DAO",
"image": "http://asset.benswap.cash/tokens/0xca0235058985fcC1839E9e37c10900a73C126708.png",
"website": "https://dao.cash",
}

SBCH first DAO token, inspired by PEOPLE's success, and now we have our own community token symbol. Just came out yesterday and now it goes viral, BCHers voluntarily solicits donations of $1000 to buy the domain name of dao.cash. Everything is on rapid growth.

Liquidity, DAO-EBEN pair is actively working on Benswap.

Check it's price chart here:  https://chartpro.benswap.cash/?token=0xca0235058985fcc1839e9e37c10900a73c126708

**Comment by webeli** [comment]
@jackhbgs website not working. Any more information? Twitter / Telegram etc?

**Comment by jackhbgs** [comment]
They just bought the domain today, the website is not built up yet. Currently, we use "bch swarm" as our official tg channel. You may want to join in and the airdrop campaign is still live. https://t.me/bchchinese

And they don't have an official Twitter at this moment as well. The project was founded yesterday and it goes viral, we have now over 5000 new members who received the airdrop DAOs.

**Comment by jackhbgs** [comment]
All DAOs will be fully distributed to people, and some will be sent to Vitalik and some charities. It was just a simple idea that came out yesterday and was supposed to be a test after seeing the success of PEOPLE, now it is absolutely out of expectation and goes viral. Jihan Wu commented on this project and he suggested donating some to Vitalik since BCH is getting some benefits from EVM.

**Comment by jackhbgs** [comment]
@webeli

**Comment by jackhbgs** [comment]
> 

@webeli

**Comment by webeli** [comment]
@jackhbgs will add it when the website is working.

**Comment by webeli** [comment]
Added.

**Comment by jackhbgs** [comment]
> Added.

Thank you very much @webeli , please leave your smartbch wallet address, I would like to airdrop some DAOs to you.
