### ISSUE TITLE
Add SIDX token

### ISSUE THREAD

**Issue by kratatomi** [MarketCap-Cash/SmartBCH-Token-List#65]
{
"name": "SmartIndex",
"desc": "First deflationary and governance token linked to a managed portfolio on SmartBCH",
"address": "0xF05bD3d7709980f60CD5206BddFFA8553176dd29",
"symbol": "SIDX",
"image": "https://smartindex.cash/SmartIndex.png",
"website": "https://smartindex.cash/",
"telegram": "https://t.me/smartindex_community",
"github": "https://github.com/kratatomi/SmartIndex"
}

**Comment by kratatomi** [comment]
There's liquidity in Tango and Mist. I can provide other images formats if needed.

**Comment by webeli** [comment]
Added.
