### ISSUE TITLE
Let's reopen this when you have liquidity, closing for now.

### ISSUE THREAD

**Issue by bchpete** [MarketCap-Cash/SmartBCH-Token-List#68]
Let's reopen this when you have liquidity, closing for now.

_Originally posted by @webeli in https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/60#issuecomment-974998380_

0x1F354956DE4A7Ed71308225De94a27b35A84EA57 Liquidity has been added on MistSwap, can you reopen now?

**Comment by webeli** [comment]
Added.
