### ISSUE TITLE
Add Xolos RMZ

### ISSUE THREAD

**Issue by Gutiman18** [MarketCap-Cash/SmartBCH-Token-List#69]
Token name: Xolos

Network: Mainnet 

Symbol: RMZ

Decimals: 18

Address:0x49F9ECF126B6dDF51C731614755508A4674bA7eD 

Website: https://www.xolosramirez.com/nft-xolos-ramirez/

Project/Token information: Xolos Ramirez NFT Metaverse Is where the Sep20 token Will have it's utility. It Is a Collection of Xoloitzcuintles with different wardrobes, hobbies, personalities and universes. They are Xolo mexican dogs with Ramirez as a last name.

Discover all possibilities within the Xolos Ramirez metaverse.

Telegram https://t.me/xolosramirez
Twitter https://www.twitter.com/xolosramirez1
Logo:
![xolosramirez](https://user-images.githubusercontent.com/68677413/144258744-040eaffd-48c4-4ff3-9ad5-8b8c5908f256.png)

**Comment by webeli** [comment]
This token is already added before?
