### ISSUE TITLE
Please add SEP-20 Token "CandyMan"

### ISSUE THREAD

**Issue by istmeprincess** [MarketCap-Cash/SmartBCH-Token-List#7]
{
"name": "CandyMan"
"address": "0x0D8b355f9CEDeB612f2df4B39CdD87059A244567"
"symbol": "CandyMan"
"image": "https://telegra.ph/file/a5a8e27e00eaa36e90ac7.png"
"website": "https://istmeprincess.github.io/CandyMan/"
"telegram": "https://t.me/CandyManToken"
}

**Comment by webeli** [comment]
Done.
