### ISSUE TITLE
Please add catsluck token--CLK into the list

### ISSUE THREAD

**Issue by jackhbgs** [MarketCap-Cash/SmartBCH-Token-List#71]
{
"name": "Catsluck",
"desc": "an official token of catsluck",
"address": "0x659F04F36e90143fCaC202D4BC36C699C078fC98",
"symbol": "CLK",
"image": "https://catsluck.com/clk.png",
"website": "https://catsluck.com/",
"telegram": "https://t.me/catsluck_english, https://t.me/catsluck_chinese"
"twitter": "..."
}

Who's behind Catsluck?

We are supporters of cashcats. People often ask what can we do with $CATS? So catsluck was born. You can bet and invest with $CATS now, and do more things in the future.

What is CLK?

CLK's address:

CLK is catsluck's exclusive token. CLK does not set a fixed upper limit. Before, users will get 1 free CLK every time he bets 1 $CATS. After that, the total amount of CLK does not increase. Till now, totally -- CLK have been minted. Please let your wallet watch CLK.

Does the development team reserve CLK?

Not at all. Absolutely fair distribution.

Where to trade CLK?

CLK/$CATS trading pair on benswap.

What is the house edge?

The house edge is 2%.

1% is allocated to the reward pool and another 1% is used to buy back CLK in circulation. Currently, there have been -- $CATS accumulated for buyback, which equals about -- CLK. Anyone can send a transaction to buy CLK with these $CATS and burn them. Till now, totally -- CLK have been bought back and burnt.

Future plans?

Code Audit
Support other tokens, such as BCH and various stable coins
Support DAO
Add the "bet on any event" function. For example, people can predict what the price of BTC is going to be a month from now? Who will win the next U.S. presidential election? Who won the World Cup final? All CLK holders can act as judges and vote with their CLK.
Is it open source?

Yes. Check it here https://github.com/catsluck/catsluck.

**Comment by jackhbgs** [comment]
@webeli thank you Webeli!

**Comment by jackhbgs** [comment]
There are almost 104M $cats locked in the catsluck pool in just 2 days.

**Comment by webeli** [comment]
We currently need minimum 0.1 BCH in TOKEN/BCH pair liquidity before listing. Still working on supporting other pairs.

**Comment by jackhbgs** [comment]
> 

Thanks for this tip. I'm adding. @webeli

**Comment by jackhbgs** [comment]
Added! @webeli 
![Screenshot_20211203_205120_vip mytokenpocket](https://user-images.githubusercontent.com/64890042/144605582-52762078-1aa0-4648-bb4d-046b11b92ee3.jpg)

**Comment by webeli** [comment]
Added.
