### ISSUE TITLE
Please add token "lawETP"

### ISSUE THREAD

**Issue by BlockNG** [MarketCap-Cash/SmartBCH-Token-List#72]
{
"name": "LAW Entropy",
"address": "0x4ee06d0486ced674E75Ed9e521725580e8ffDA21",
"symbol": "lawETP",
"image": "https://assets.benswap.cash/tokens/0x4ee06d0486ced674E75Ed9e521725580e8ffDA21.png",
"website": "https://blockng.money/#/",
"telegram": "https://t.me/BlockNGGlobal"
}

**Comment by webeli** [comment]
Please add atleast 0.5 BCH/LAWETP liquidity to any DEX.

**Comment by BlockNG** [comment]
The main liquidity of lawETP is in this trading pair.
https://info.benswap.cash/pair/0x88b2522b9f9121b3e19a28971a85d34d88e4acc6

In fact it is already deeper than 0.5BCH, so it may require some special handling.

**Comment by webeli** [comment]
@BlockNG got it, unfortunately we currently only support TOKEN/BCH pairs. Working on automatically supporting whiteflagged pairs.

**Comment by JamesLHW** [comment]
@webeli 
{
"name": "LAW Entropy",
"address": "0x4ee06d0486ced674E75Ed9e521725580e8ffDA21",
"symbol": "lawETP",
"image": "https://assets.benswap.cash/tokens/0x4ee06d0486ced674E75Ed9e521725580e8ffDA21.png",
"website": "https://blockng.money/#/",
"telegram": "https://t.me/BlockNGGlobal"
}
lawETP/BCH liquidity:
https://info.benswap.cash/pair/0xdcd2e7ff8c6c9a95ec26411630a3dde87e0857ed

**Comment by webeli** [comment]
Added.
