### ISSUE TITLE
Listing of Wenlambo

### ISSUE THREAD

**Issue by wenlambotoken** [MarketCap-Cash/SmartBCH-Token-List#77]
{
"name": "Wenlambo",
"address": "0x0E36C351ff40183435C9Bd1D17bfb1F3548f1963",
"symbol": "LAMBO",
"image": "https://i.pinimg.com/originals/3e/15/8d/3e158d40d62afae0c1d0da9f6291a8ec.jpg",
"telegram": "https://t.me/wenlambotoken",
}

**Comment by webeli** [comment]
Added.
