### ISSUE TITLE
Add SmartDoge (SMART) to token list

### ISSUE THREAD

**Issue by smartdogebch** [MarketCap-Cash/SmartBCH-Token-List#78]
"SMART": {
  "address": "0x6e6D4ECE35EEd638A1153339F69E543B7ae5F776",
  "desc": "A hyper-deflationary fluffy token with automatic reflections on SmartBCH",
  "image": "https://github.com/smartdogebch/assets/blob/main/smartdoge-icon.png",
  "name": "SmartDoge",
  "symbol": "SMART",
  "Telegram": ["https://t.me/smartdogebchofficial"]
  "websites": ["https://smartdoge.cash"]
  "twitter": "https://twitter.com/smartdogebch"
}

**Comment by smartdogebch** [comment]
Hi, it's been 3 days now, is there anything else I need to add to the listing form?

**Comment by webeli** [comment]
@smartdogebch very confused about this project, seems like a copy of dogecoin/safemoon but it's also a DEX? Please give us more information.

**Comment by smartdogebch** [comment]
SmartDoge is essentially a fair form of a pre-sale for the upcoming SmartDex. It's a reflection coin, yes, but it is not trying to capitalize on DogeCoin or SHIBA INU by any stretch of the imagination, as it's nurturing its own brand and style. By buying the SmartDoge token, you are given extra rights in the SmartDex and you'll be able to accrue 1/3 of the upcoming DEX's fees, while also enjoying native self-reflections. It's a project designed by me (website, coding, community outreach), Sergei, and we're using a nice and loveable Weibo-inspired dog design in order to stand out :)

Hope that answers your question.

PS: We have about 9k USD liquidity, up from 7k USD when we last talked.

**Comment by jQrgen** [comment]
Much wow! Very accept merge request.

**Comment by webeli** [comment]
Added.
