### ISSUE TITLE
Please help to replace Catsluck logo

### ISSUE THREAD

**Issue by jackhbgs** [MarketCap-Cash/SmartBCH-Token-List#80]
Hi @webeli ,

Please help to replace catsluck logo. The catsluck team had replied to me and would like to take this new logo very much. Here I attach the PNG files in different sizes, check them out.

Btw, Benswap has already helped to change the icon for catsluck.

Thank you.

**Screenshot of me&catsluck chat:** 
![catsluck reply](https://user-images.githubusercontent.com/64890042/145145792-f10706a6-6d16-4dcc-bcba-5ed421b2d900.png)

**Catsluck new logo in different sizes:**
![512](https://user-images.githubusercontent.com/64890042/145145652-c5b8de3f-5354-46ad-9be2-90e909072363.jpg)
![32](https://user-images.githubusercontent.com/64890042/145145658-db1dfa6e-771c-49df-83bd-be50d1204ad1.jpg)
![24](https://user-images.githubusercontent.com/64890042/145145660-5d3dc395-fbaa-4223-900b-c9d1fb8f9dcf.jpg)
![16](https://user-images.githubusercontent.com/64890042/145145661-5211755c-ea2b-45e7-809b-3ce93a1ddea9.jpg)

**Comment by jackhbgs** [comment]
The website has just adopted the new logo!

![catsluck adopted new logo](https://user-images.githubusercontent.com/64890042/145146938-05a1b7e1-1aad-4089-bc44-9fde87330565.jpg)

**Comment by webeli** [comment]
Done.
