### ISSUE TITLE
DCC token - The collaborative token

### ISSUE THREAD

**Issue by clixmoney** [MarketCap-Cash/SmartBCH-Token-List#82]
I'm the founder of DCooperation community. I created it on steem, and now we are mostly active in hive. 

I would like to see the token created on SmartBCH as well. 

Before creating the token I would like to know what's the minimum liquidity I can add ?

**Comment by webeli** [comment]
0.5 BCH for stability.

**Comment by webeli** [comment]
@clixmoney any updates here? closing this now, please reopen when you've created your token.
