### ISSUE TITLE
Please add coin DONER

### ISSUE THREAD

**Issue by jQrgen** [MarketCap-Cash/SmartBCH-Token-List#83]
{
        "name": "Döner",
        "address": "0x14d9337f86d51dcad0d28f6439e00039e251b592",
        "desc": "DONER is the official fan and experimentation token channel for Döner Tallrik and Dj Bord on SmartBCH. Our goal is to create an artist collective DAO that owns itself and pays the creators directly in money and voting power.",
        "symbol": "DONER",
        "image": "https://i.imgur.com/E2OWRmL.png",
        "telegram": "https://t.me/wenlambotoken",
        "twitter": "https://twitter.com/donertallrik",
        "websites": ["https://donertallrik.web.app", "https://opensea.io/collection/doner", "https://soundcloud.com/user-688920568-653173414"]
  },

**Comment by webeli** [comment]
"telegram": "https://t.me/wenlambotoken" ?

**Comment by jQrgen** [comment]
Oops! One second.

**Comment by jQrgen** [comment]
@webeli Updated! Does it look ok now? Thanks.

**Comment by jQrgen** [comment]
Airdropping DONER to 260 people now :O
