### ISSUE TITLE
MGOT

### ISSUE THREAD

**Issue by iammultiman** [MarketCap-Cash/SmartBCH-Token-List#9]
{
"name": "MGOT",
"address": "0x7DF65F158126898725f262378538B60db543C11A",
"symbol": "MGOT",
"image": "https://storageapi.fleek.co/iammultiman-team-bucket/icons/Mota-Global-Operational-Token-2.png",
"website": "https://motaglobal.club/online/",
"telegram": "https://t.me/mgot_token.",
"twitter": "https://twitter.com/MotaGlobal"
}

**Comment by webeli** [comment]
Can't find any transactions on that address @iammultiman, is it correct?
https://www.smartscan.cash/address/0x7DF65F158126898725f262378538B60db543C11A

**Comment by iammultiman** [comment]
Yes it is correct. Tokens have not been issued

**Comment by webeli** [comment]
@iammultiman you need to have onchain liquidity (like on benswap.cash) for marketcap.cash to collect data. When you have that, we can add it.

**Comment by webeli** [comment]
Added.
