### ISSUE TITLE
Please Add FireDao 

### ISSUE THREAD

**Issue by Diggle187** [MarketCap-Cash/SmartBCH-Token-List#90]
Name:FireDAO
Symbol:FIREDAO
Total Supply:210,000,000,000
Circulating Supply: 118746582018.08105
Image: 
![2F793899-0E3F-42AA-B8C5-09FD9935C16B](https://user-images.githubusercontent.com/90625656/145732703-85fab064-172c-4f12-a7b7-c53305dfb8e1.jpeg)
Decimals:18
Contract Address:0xd8AEdd78dEB34fD29589aC4C8B3eb0435d5a61bb
Telegram: https://t.me/FireDAOsmartbch
Twitter: https://twitter.com/fire_dao_sbch?s=21

FireDao is 100% community lead, with this massive burning system and tax distribution. FireDao has deflationary features that constantly burning 5% on every transaction, respectively distributing 3% on every holder and 2% back to liquidity regeneration. The 40% token sent to blackhole.

**Comment by webeli** [comment]
Is this coin still relevant? where's liquidity?

**Comment by webeli** [comment]
No update to latest question, closing for now, please reopen if still relevant.
