### ISSUE TITLE
Please list Narath, Konra's sister Token

### ISSUE THREAD

**Issue by KonraToken** [MarketCap-Cash/SmartBCH-Token-List#93]
Please list Narath on Market Cap Cash:

{
"name": "Narath",
"desc": "Narath is the sister token to Konra. It's a reward token meant to serve as an incentive for those who further SmartBCH and help out in the Konra Project. Narath features a plentiful supply which is only gradually released over the next 6 + years as a good amount of the supply is locked up in a series of time locks.",
"address": "0x0cb20466c0dd6454acf50ec26f3042ccc6362fa0",
"symbol": "NARATH",
"image": "https://konratoken.com/wp-content/uploads/2021/12/NarathLogo.png",
"website": "https://konratoken.com/Narath",
"twitter": "https://twitter.com/KonraToken"
}

Other relevant info you may need:

Total Supply: 300,000,000,000
Decimals: 18
Minting Baton: Closed
Burnable: Yes
Contract Address: 0x0cb20466c0dd6454acf50ec26f3042ccc6362fa0

It's already on DexScanner and took the market by surprise yesterday night upon launching so here is my quick application to list it on Market Cap Cash.

Twitter: Announcements will be made over the KonraToken twitter account
Website: https://konratoken.com/Narath
I also post about it on NoiseCash:  https://noise.cash/u/TheEmpress

Liquidity on BenSwap, MistSwap and 1BCH Dex, all under the Narath - BCH pairing; good trading volume on all three DEX's.

I edited this to put it into the proper format....

**Comment by Pippex** [comment]
https://konratoken.com/Narath/ Instead https://konratoken/Narath xD

**Comment by webeli** [comment]
Added.
