### ISSUE TITLE
Please Add STO

### ISSUE THREAD

**Issue by tokenobserver** [MarketCap-Cash/SmartBCH-Token-List#94]
"STO": 
    "address": "0xAFACB0004A91267b58e720E13DF570Dc6863c854",
    "desc": "STO is a project aiming at protecting BCH ecosystem. We will review the new projects and provide investors with our judgements by doing in-depth research and analysis.",
    "name": "SmartBCH Token Observer",
    "symbol": "STO",
    "telegram": "https://t.me/TokenObserverBCH"
    "twitter": "https://twitter.com/STOsmartBCH"

![22](https://user-images.githubusercontent.com/92710291/146500672-e2f4d6f3-8377-43e3-9541-1b2f1a4910dd.png)

Liquidity: https://app.mistswap.fi/swap?inputCurrency=&outputCurrency=0xAFACB0004A91267b58e720E13DF570Dc6863c854

**Comment by webeli** [comment]
Added.
