### ISSUE TITLE
Kindly Add Metador $Meta to marketcap.cash

### ISSUE THREAD

**Issue by Metador-SMARTBCH** [MarketCap-Cash/SmartBCH-Token-List#98]
Name: Metador
Description: Metador, A virtual project founded on SmartBCH Chain. It can be illustrated as an iteration of the internet, supporting persistent online 3-D virtual environments.
Symbol: META
Address: 0x7e56D225f69A5b0D1C2FC47673A5c41328fC82e0
Image: 
![logo](https://user-images.githubusercontent.com/95138869/146630010-7007d665-2754-4765-92a0-f726ae4e4cfe.png)
Website: https://smetador.space
Twitter: https://twitter.com/Metador_SBCH
Liquidity added on MistSwap.

**Comment by webeli** [comment]
Added.
